### ISSUE TITLE
Optional root privileges

### ISSUE THREAD

**Issue by MarcRdC** [wolpi/prim-ftpd#55]
Is it possible to run Primitive FTPd with root privileges and browse/modify system folders/files?

**Comment by wolpi** [comment]
Might be added in a future version. It will probably take some months until I find time for it.

**Comment by MarcRdC** [comment]
O.K., thanks. I will be watching further development of the application.

**Comment by wolpi** [comment]
As far as I could figure it out it is not possible to run the existing java code of this app as root. Instead it is necessary to launch external processes as root and parse their output. It will take some time to implement this.

**Comment by Dark-Noir** [comment]
I also need this app with root permission because, only with root i can read/write on my external storage.

**Comment by mbnoimi** [comment]
Thumb up for root support.

**Comment by wolpi** [comment]
root is done :tada:

**Comment by MarcRdC** [comment]
Thank you for your work.

**Comment by Dark-Noir** [comment]
Yeah thanks, is system-less root "Magisk" supported or only things like SuperSU?

**Comment by wolpi** [comment]
it's SuperSU

**Comment by mbnoimi** [comment]
Crashes !!!

![apps2sd-scr_10_6_2017_6_4_57](https://user-images.githubusercontent.com/284547/32423782-9f1a59c8-c2b9-11e7-81e6-b6433886f0c1.gif)

**Comment by wolpi** [comment]
> Crashes !!!

can you post logs?

**Comment by mbnoimi** [comment]
@wolpi 

> can you post logs?

Where can I find it?

**Comment by wolpi** [comment]
Well, as you cannot even see main activity your only chance is to get android system logs. One way to do that is to use commandline tool `adb` from android sdk. Do you need help with that?

**Comment by wolpi** [comment]
Did a previous version work on your device?
Do you have a custom rom?

A change for main activity in recent version is a group of radio buttons. They should not cause such a crash 😭

**Comment by mbnoimi** [comment]
> Did a previous version work on your device?

The old versions were working fine (before version 5)

>  Do you have a custom rom?

No I used the original ROM from ASUS the only change occurred is rooting the ROM using ``adb``

> A change for main activity in recent version is a group of radio buttons. They should not cause such a crash :sob:

After updating to the new version (5.1) I able to send the crash log using Google Play Feedback so I sent 4 reports to you using my email address mbnoimi {at} gmail dot com

**Comment by wolpi** [comment]
>  I able to send the crash log using Google Play Feedback 

Thats Great 👍 
Release with fixes is on it's way 😄

**Comment by mbnoimi** [comment]
> Release with fixes is on it's way :smile:

Same problem with recent version 5.2 (send the feedback using Google Play)

**Comment by wolpi** [comment]
> Same problem with recent version 5.2 (send the feedback using Google Play)

It seems you have an android version older than lollipop. I fixed those crashes but you won't be able to use root or SAF.

**Comment by mbnoimi** [comment]
> It seems you have an android version older than lollipop.

As mentioned in the gif above. I use Android 4.4.2

> I fixed those crashes but you won't be able to use root or SAF.

Indeed I can run the app without problem now (ver. 5.3) but unfortunately without root access it's a useless app :(

**Comment by wolpi** [comment]
Just for you: I refactored code a little to provide root for android 4 😉

**Comment by mbnoimi** [comment]
Thanks @wolpi 
> Just for you: I refactored code a little to provide root for android 4 :wink:

Still doesn't work fine. The server got root privileges correctly but my FTP client unable to retrieve folders list. I tried many FTP clients but I got same result each time!

```
Status:	Disconnected from server
Status:	Connecting to 192.168.1.104:1234...
Status:	Connection established, waiting for welcome message...
Response:	220 Service ready for new user.
Command:	AUTH TLS
Response:	431 Service is unavailable.
Command:	AUTH SSL
Response:	431 Service is unavailable.
Status:	Insecure server, it does not support FTP over TLS.
Command:	USER mbnoimi
Response:	331 User name okay, need password for mbnoimi.
Command:	PASS *********
Response:	230 User logged in, proceed.
Command:	OPTS UTF8 ON
Response:	200 Command OPTS okay.
Command:	OPTS MLST size;modify;type;
Response:	200 Command OPTS okay.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/storage/MicroSD" is current directory.
Status:	Directory listing of "/storage/MicroSD" successful
Status:	Retrieving directory listing of "/storage/MicroSD"...
Command:	TYPE I
Response:	200 Command TYPE okay.
Command:	PASV
Response:	227 Entering Passive Mode (192,168,1,104,206,125)
Command:	MLSD
Response:	150 File status okay; about to open data connection.
Response:	226 Closing data connection.
Status:	Directory listing of "/storage/MicroSD" successful
Status:	Retrieving directory listing of "/storage"...
Command:	CDUP
Response:	550 No such directory.
Error:	Failed to retrieve directory listing
```

**Comment by mbnoimi** [comment]
### Content of prim-ftpd-log.csv
```
"2017-06-24 07:10:30.26";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onResume()";"";
"2017-06-24 07:10:30.29";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2017-06-24 07:10:30.30";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2017-06-24 07:10:30.37";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates(), no icons";"";
"2017-06-24 07:10:30.48";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"network connectivity changed, data str: 'null', action: 'android.net.conn.CONNECTIVITY_CHANGE'";"";
"2017-06-24 07:10:30.52";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"addr: '/fe80::a62:66ff:fe1a:33d4%wlan0%6', iface name: 'wlan0', disp name: 'wlan0', loopback: 'fa...";"";
"2017-06-24 07:10:30.53";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"Skipping IPv6 address 'fe80::a62:66ff:fe1a:33d4%wlan0 (wlan0)'";"";
"2017-06-24 07:10:30.53";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"addr: '/192.168.1.104', iface name: 'wlan0', disp name: 'wlan0', loopback: 'false'";"";
"2017-06-24 07:10:30.55";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"addr: '/::1%1%1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2017-06-24 07:10:30.56";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"addr: '/127.0.0.1', iface name: 'lo', disp name: 'lo', loopback: 'true'";"";
"2017-06-24 07:10:30.157";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onCreateOptionsMenu()";"";
"2017-06-24 07:10:30.159";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"displayServersState()";"";
"2017-06-24 07:10:30.160";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"checkServicesRunning()";"";
"2017-06-24 07:10:30.167";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"updateButtonStates()";"";
"2017-06-24 07:10:33.488";"DEBUG";"org.primftpd.PrimitiveFtpdActivity";"onPause()";"";
```

**Comment by mbnoimi** [comment]
### Content of ``org.primftpd_preferences.xml``

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <string name="startDirPref">/storage/MicroSD</string>
    <string name="securePortPref">2223</string>
    <boolean name="pubKeyAuthPref" value="false" />
    <boolean name="foregroundServicePref" value="true" />
    <string name="userNamePref">mbnoimi</string>
    <string name="passwordPref">3O9RbBvL8DzKyNb/ZtBopJKuwieTctDFBtFGENpCY78l3ChBW8bOl1bIT+kvuq7FHMvpaJxixi+QMea/r6cvbg==</string>
    <string name="themePref">0</string>
    <boolean name="startOnBootPref" value="false" />
    <string name="whichServerToStartPref">1</string>
    <boolean name="anonymousLoginPref" value="false" />
    <string name="loggingPref">0</string>
    <boolean name="announcePref" value="false" />
    <string name="announceNamePref">primitive ftpd</string>
    <string name="portPref">1234</string>
    <string name="storageTypePref">2</string>
    <boolean name="wakelockPref" value="true" />
</map>
```

**Comment by wolpi** [comment]
> Content of prim-ftpd-log.csv

That log is about displaying UI. The intresting part is missing there 😭 

The app keeps 3 log files with timestamps in their name. Usually it is the 2nd of those 3 files that contains intresting information.

**Comment by wolpi** [comment]
@mbnoimi could you share more logs?

**Comment by mbnoimi** [comment]
> The app keeps 3 log files with timestamps in their name. Usually it is the 2nd of those 3 files that contains intresting information.

What's the path of these files?

**Comment by wolpi** [comment]
> What's the path of these files?

They are all located in the same directory (the default home dir, it is different on devices, often it is `/storage/emulated/0`). As you posted already some logs I thought it would be easy 😄

**Comment by mbnoimi** [comment]
Unfortunately I upgraded my phone to Android 5 yesterday

**Comment by wolpi** [comment]
> Unfortunately I upgraded my phone to Android 5 yesterday

Do you still have issues with this app?
